// Builds a single-file executable that carries the API contracts inside it.
//
// The npm package reads contracts from dist/contracts/ next to the built CLI.
// A compiled binary has no such directory — Bun's bundler cannot see a runtime
// `readFile(new URL(...))`, so the contracts would be missing and every `api`
// command would fail with ENOENT on /$bunfs. This script therefore generates an
// entry point that injects the contracts as strings before dispatching.
//
// Strings, not parsed objects: the bundle carries ~750 KB of contract text that
// stays unparsed until a command needs one version, so startup does not pay for
// six API snapshots.
import { readdir, readFile, rm } from "node:fs/promises";
import { basename, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const dist = resolve(root, "dist");
const contractsDirectory = resolve(dist, "contracts");

// `--target` selects one of Bun's `bun-<os>-<arch>` triplets. Without it Bun
// compiles for the host, which is what a local `bun run compile` wants; the
// release pipeline names a target explicitly so the asset it produces is
// unambiguous even when the runner could have been guessed wrong.
let target: string | undefined;
let positional: string | undefined;
for (let index = 2; index < process.argv.length; index++) {
  const argument = process.argv[index]!;
  if (argument === "--target") {
    target = process.argv[++index];
    if (!target) {
      process.stderr.write("--target requires a value, e.g. bun-linux-x64\n");
      process.exit(1);
    }
  } else if (argument.startsWith("--target=")) {
    target = argument.slice("--target=".length);
  } else if (argument.startsWith("-")) {
    process.stderr.write(`Unknown option: ${argument}\n`);
    process.exit(1);
  } else if (positional === undefined) {
    positional = argument;
  } else {
    process.stderr.write(`Unexpected argument: ${argument}\n`);
    process.exit(1);
  }
}

const outFile = positional
  ? resolve(process.cwd(), positional)
  : resolve(dist, "langfuse-cli");

let entries: string[];
try {
  entries = await readdir(contractsDirectory);
} catch {
  process.stderr.write(
    "dist/contracts is missing; run `bun run build` before `bun run compile`\n",
  );
  process.exit(1);
}

const contracts = new Map<string, string>();
for (const entry of entries) {
  if (!entry.endsWith(".json")) continue;
  const key = basename(entry, ".json");
  contracts.set(key, await readFile(resolve(contractsDirectory, entry), "utf8"));
}
if (!contracts.has("catalog")) {
  process.stderr.write("dist/contracts/catalog.json is missing\n");
  process.exit(1);
}

// JSON.stringify escapes the payload into a valid TypeScript string literal.
const injected = [...contracts]
  .map(([key, source]) => `  ${JSON.stringify(key)}: ${JSON.stringify(source)},`)
  .join("\n");

const entryPath = resolve(dist, "compile-entry.ts");
await Bun.write(
  entryPath,
  `// Generated by scripts/compile.ts — do not edit.
import { run } from "../src/cli";
import { setEmbeddedContracts } from "../src/contracts/loader";

setEmbeddedContracts({
${injected}
});

await run(process.argv);
`,
);

const result = Bun.spawnSync([
  "bun",
  "build",
  "--compile",
  "--minify",
  ...(target ? [`--target=${target}`] : []),
  entryPath,
  "--outfile",
  outFile,
]);
await rm(entryPath, { force: true });

if (result.exitCode !== 0) {
  process.stderr.write(new TextDecoder().decode(result.stderr));
  process.exit(result.exitCode ?? 1);
}

// Bun appends .exe when it compiles for Windows and the name lacks it.
const written = (await Bun.file(outFile).exists()) ? outFile : `${outFile}.exe`;
const size = (await Bun.file(written).stat()).size;
process.stdout.write(
  `Compiled ${written} (${(size / 1024 / 1024).toFixed(1)} MB) with ${contracts.size - 1} embedded contracts\n`,
);
